version: '3.8'

services:
  
  queue-broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"       
      - "15672:15672"     

  humidity-sensor:
    build:
      context: .
      dockerfile: ./services/humidity-sensor/Dockerfile
    restart: always
    depends_on:
      - queue-broker
    environment:
      - BROKER_HOST=queue-broker

  wind-sensor:
    build: ./services/wind-sensor
    restart: always
    depends_on:
      - queue-broker
    environment:
      - BROKER_HOST=queue-broker

  humidity-dashboard:
    build:
      context: .
      dockerfile: ./services/humidity-dashboard/Dockerfile
    restart: always
    ports:
      - "8080:8080"       
    depends_on:
      - queue-broker
    environment:
      - BROKER_HOST=queue-broker